#
###################################
# Site wide configuration
####################################
#
---
title: Dustin McClure | Portfolio
email: frankzappasmustache@protonmail.com
description: Dustin McClure's Website and Portfolio
url: https://frankzappasmustache.github.io
keywords: [
  "portfolio",
  "blog",
  "CV",
  "jekyll",
  "developer",
  "code",
  "back-end developer",
  "web developer"
]

#
###################################
# Jekyll configuration
####################################
#
timezone: US/Pacific
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Dustin McClure
  avatar: frankzappasmustache-logo.jpg
  job: "Support Engineer"
  bio: "Welcome to my portfolio<br />I am a nerd, a tinkerer, and have too many interests."
  email: frankzappasmustache@protonmail.com
  forhire: true
  disqus-shortname:  # username
  twitter:  # username
  facebook:  # username
  google:
    plus:  # username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: frankzappasmustache
  gitlab: frankzappasmustache
  stackoverflow: 6369376/frankzappasmustache  # 123456/username
  # from a "http://stackoverflow.com/users/123456/username" link
  linkedin: dustin-mcclure-8004583b
  skype:  # username
  xing:  # username
  instagram: frank_zappas_mustache
  lastfm:  # username
  tumblr:  # username
  pinterest:  # username
  foursquare:  # username
  steam:  # username
  dribbble:  # username
  youtube:  # username
  soundcloud:  # username
  weibo:  # username
  flickr:  # username
  500px:  # username
  codepen: frankzappasmustache
  reddit:  # username
  telegram:  # username
